import { readSchwabPositions } from "../read-schwab-positions";
import { getMockDataFile } from "../../utils/testing/get-mock-data-file.ts";

it("schwab positions are correctly read", async () => {
  expect(
    await readSchwabPositions(
      getMockDataFile("schwab-account-positions.csv"),
    ),
  ).toMatchObject({
    "EF2": {
      "BSV": {
        "Description": "VANGUARD SHORT-TERM BONDETF",
        "Qty (Quantity)": 70,
        "Price": 77.64,
        "Price Chng % (Price Change %)": 0.0013,
        "Price Chng $ (Price Change $)": 0.1,
        "Mkt Val (Market Value)": 5434.8,
        "Day Chng % (Day Change %)": 0.0013,
        "Day Chng $ (Day Change $)": 7,
        "Cost Basis": 5305.17,
        "Gain % (Gain/Loss %)": 0.024399999999999998,
        "Gain $ (Gain/Loss $)": 129.63,
        "Ratings": null,
        "Reinvest?": "No",
        "Reinvest Capital Gains?": null,
        "% of Acct (% of Account)": 0.25370000000000004,
        "Security Type": "ETFs & Closed End Funds"
      },
      "VTIP": {
        "Description": "VANGUARD SHRT INF PROT SEC INDEX ETF",
        "Qty (Quantity)": 14,
        "Price": 48.97,
        "Price Chng % (Price Change %)": 0.0012,
        "Price Chng $ (Price Change $)": 0.06,
        "Mkt Val (Market Value)": 685.58,
        "Day Chng % (Day Change %)": 0.0012,
        "Day Chng $ (Day Change $)": 0.84,
        "Cost Basis": 662.97,
        "Gain % (Gain/Loss %)": 0.0341,
        "Gain $ (Gain/Loss $)": 22.61,
        "Ratings": null,
        "Reinvest?": "No",
        "Reinvest Capital Gains?": null,
        "% of Acct (% of Account)": 0.032,
        "Security Type": "ETFs & Closed End Funds"
      },
      "DFGFX": {
        "Description": "DFA TWO-YEAR GLOBAL FIXED-INCOME I",
        "Qty (Quantity)": 1,
        "Price": 9.9,
        "Price Chng % (Price Change %)": null,
        "Price Chng $ (Price Change $)": null,
        "Mkt Val (Market Value)": 11058.3,
        "Day Chng % (Day Change %)": null,
        "Day Chng $ (Day Change $)": null,
        "Cost Basis": 11061.29,
        "Gain % (Gain/Loss %)": -0.0003,
        "Gain $ (Gain/Loss $)": -2.99,
        "Ratings": 4,
        "Reinvest?": "No",
        "Reinvest Capital Gains?": "No",
        "% of Acct (% of Account)": 0.5161,
        "Security Type": "Mutual Fund"
      },
      "SWRSX": {
        "Description": "SCHWAB TREASURY INFL PROTECTED SECS IDX",
        "Qty (Quantity)": 143,
        "Price": 10.28,
        "Price Chng % (Price Change %)": 0.0029,
        "Price Chng $ (Price Change $)": 0.03,
        "Mkt Val (Market Value)": 1470.04,
        "Day Chng % (Day Change %)": 0.0029,
        "Day Chng $ (Day Change $)": 4.29,
        "Cost Basis": 1593.06,
        "Gain % (Gain/Loss %)": -0.07719999999999999,
        "Gain $ (Gain/Loss $)": -123.02,
        "Ratings": 4,
        "Reinvest?": "No",
        "Reinvest Capital Gains?": "No",
        "% of Acct (% of Account)": 0.06860000000000001,
        "Security Type": "Mutual Fund"
      },
      "SWTSX": {
        "Description": "SCHWAB TOTAL STOCK MARKET INDEX",
        "Qty (Quantity)": 27,
        "Price": 102.86,
        "Price Chng % (Price Change %)": -0.0034000000000000002,
        "Price Chng $ (Price Change $)": -0.35,
        "Mkt Val (Market Value)": 2777.22,
        "Day Chng % (Day Change %)": -0.0034000000000000002,
        "Day Chng $ (Day Change $)": -9.45,
        "Cost Basis": 1457.67,
        "Gain % (Gain/Loss %)": 0.9052,
        "Gain $ (Gain/Loss $)": 1319.55,
        "Ratings": 3,
        "Reinvest?": "No",
        "Reinvest Capital Gains?": "No",
        "% of Acct (% of Account)": 0.12960000000000002,
        "Security Type": "Mutual Fund"
      },
      "Cash & Cash Investments": {
        "Description": null,
        "Qty (Quantity)": null,
        "Price": null,
        "Price Chng % (Price Change %)": null,
        "Price Chng $ (Price Change $)": null,
        "Mkt Val (Market Value)": 0,
        "Day Chng % (Day Change %)": 0,
        "Day Chng $ (Day Change $)": 0,
        "Cost Basis": null,
        "Gain % (Gain/Loss %)": null,
        "Gain $ (Gain/Loss $)": null,
        "Ratings": null,
        "Reinvest?": null,
        "Reinvest Capital Gains?": null,
        "% of Acct (% of Account)": null,
        "Security Type": "Cash and Money Market"
      },
      "Account Total": {
        "Description": null,
        "Qty (Quantity)": null,
        "Price": null,
        "Price Chng % (Price Change %)": null,
        "Price Chng $ (Price Change $)": null,
        "Mkt Val (Market Value)": 21425.94,
        "Day Chng % (Day Change %)": 0.0001,
        "Day Chng $ (Day Change $)": 2.68,
        "Cost Basis": 20080.16,
        "Gain % (Gain/Loss %)": 0.067,
        "Gain $ (Gain/Loss $)": 1345.78,
        "Ratings": null,
        "Reinvest?": null,
        "Reinvest Capital Gains?": null,
        "% of Acct (% of Account)": null,
        "Security Type": null
      }
    },
    "LPS": {
      "BND": {
        "Description": "VANGUARD TOTAL BOND MARKET ETF",
        "Qty (Quantity)": 34,
        "Price": 73.33,
        "Price Chng % (Price Change %)": 0.0027,
        "Price Chng $ (Price Change $)": 0.2,
        "Mkt Val (Market Value)": 2493.22,
        "Day Chng % (Day Change %)": 0.0027,
        "Day Chng $ (Day Change $)": 6.8,
        "Cost Basis": 2383.91,
        "Gain % (Gain/Loss %)": 0.045899999999999996,
        "Gain $ (Gain/Loss $)": 109.31,
        "Ratings": null,
        "Reinvest?": "No",
        "Reinvest Capital Gains?": null,
        "% of Acct (% of Account)": 0.0722,
        "Security Type": "ETFs & Closed End Funds"
      },
      "DFIC": {
        "Description": "DIMENSIONAL INTERN CORE EQUITY 2 ETF",
        "Qty (Quantity)": 31,
        "Price": 26.52,
        "Price Chng % (Price Change %)": 0.006500000000000001,
        "Price Chng $ (Price Change $)": 0.17,
        "Mkt Val (Market Value)": 822.12,
        "Day Chng % (Day Change %)": 0.006500000000000001,
        "Day Chng $ (Day Change $)": 5.27,
        "Cost Basis": 753.81,
        "Gain % (Gain/Loss %)": 0.0906,
        "Gain $ (Gain/Loss $)": 68.31,
        "Ratings": null,
        "Reinvest?": "Yes",
        "Reinvest Capital Gains?": null,
        "% of Acct (% of Account)": 0.023799999999999998,
        "Security Type": "ETFs & Closed End Funds"
      },
      "VNQ": {
        "Description": "VANGUARD REAL ESTATE ETF",
        "Qty (Quantity)": 26,
        "Price": 98.6,
        "Price Chng % (Price Change %)": 0.0064,
        "Price Chng $ (Price Change $)": 0.63,
        "Mkt Val (Market Value)": 2563.6,
        "Day Chng % (Day Change %)": 0.0064,
        "Day Chng $ (Day Change $)": 16.38,
        "Cost Basis": 2319.13,
        "Gain % (Gain/Loss %)": 0.1054,
        "Gain $ (Gain/Loss $)": 244.47,
        "Ratings": null,
        "Reinvest?": "No",
        "Reinvest Capital Gains?": null,
        "% of Acct (% of Account)": 0.0742,
        "Security Type": "ETFs & Closed End Funds"
      },
      "VASIX": {
        "Description": "VANGUARD LIFESTRATEGY INCOME INV",
        "Qty (Quantity)": 1,
        "Price": 15.73,
        "Price Chng % (Price Change %)": 0.0019,
        "Price Chng $ (Price Change $)": 0.03,
        "Mkt Val (Market Value)": 22226.49,
        "Day Chng % (Day Change %)": 0.0019,
        "Day Chng $ (Day Change $)": 42.39,
        "Cost Basis": 22756.45,
        "Gain % (Gain/Loss %)": -0.0233,
        "Gain $ (Gain/Loss $)": -529.96,
        "Ratings": 3,
        "Reinvest?": "Yes",
        "Reinvest Capital Gains?": "Yes",
        "% of Acct (% of Account)": 0.6431999999999999,
        "Security Type": "Mutual Fund"
      },
      "VBTLX": {
        "Description": "VANGUARD TOTAL BOND MARKET INDEX ADM",
        "Qty (Quantity)": 669,
        "Price": 9.64,
        "Price Chng % (Price Change %)": 0.0021,
        "Price Chng $ (Price Change $)": 0.02,
        "Mkt Val (Market Value)": 6449.16,
        "Day Chng % (Day Change %)": 0.0021,
        "Day Chng $ (Day Change $)": 13.38,
        "Cost Basis": 6592.06,
        "Gain % (Gain/Loss %)": -0.0217,
        "Gain $ (Gain/Loss $)": -142.9,
        "Ratings": 3,
        "Reinvest?": "No",
        "Reinvest Capital Gains?": "No",
        "% of Acct (% of Account)": 0.1866,
        "Security Type": "Mutual Fund"
      },
      "Cash & Cash Investments": {
        "Description": null,
        "Qty (Quantity)": null,
        "Price": null,
        "Price Chng % (Price Change %)": null,
        "Price Chng $ (Price Change $)": null,
        "Mkt Val (Market Value)": 0,
        "Day Chng % (Day Change %)": 0,
        "Day Chng $ (Day Change $)": 0,
        "Cost Basis": null,
        "Gain % (Gain/Loss %)": null,
        "Gain $ (Gain/Loss $)": null,
        "Ratings": null,
        "Reinvest?": null,
        "Reinvest Capital Gains?": null,
        "% of Acct (% of Account)": null,
        "Security Type": "Cash and Money Market"
      },
      "Account Total": {
        "Description": null,
        "Qty (Quantity)": null,
        "Price": null,
        "Price Chng % (Price Change %)": null,
        "Price Chng $ (Price Change $)": null,
        "Mkt Val (Market Value)": 34554.59,
        "Day Chng % (Day Change %)": 0.0024,
        "Day Chng $ (Day Change $)": 84.22,
        "Cost Basis": 34805.36,
        "Gain % (Gain/Loss %)": -0.0072,
        "Gain $ (Gain/Loss $)": -250.77,
        "Ratings": null,
        "Reinvest?": null,
        "Reinvest Capital Gains?": null,
        "% of Acct (% of Account)": null,
        "Security Type": null
      }
    },
    "IRA": {
      "BND": {
        "Description": "VANGUARD TOTAL BOND MARKET ETF",
        "Qty (Quantity)": 261.9376,
        "Price": 73.33,
        "Price Chng % (Price Change %)": 0.0027,
        "Price Chng $ (Price Change $)": 0.2,
        "Mkt Val (Market Value)": 19207.88,
        "Day Chng % (Day Change %)": 0.0027,
        "Day Chng $ (Day Change $)": 52.39,
        "Cost Basis": 18779.9,
        "Gain % (Gain/Loss %)": 0.022799999999999997,
        "Gain $ (Gain/Loss $)": 427.98,
        "Ratings": null,
        "Reinvest?": "Yes",
        "Reinvest Capital Gains?": null,
        "% of Acct (% of Account)": 0.0529,
        "Security Type": "ETFs & Closed End Funds"
      },
      "DFEM": {
        "Description": "DIMENSIONAL EMERG MARK CRE EQY 2 ETF",
        "Qty (Quantity)": 586.6274,
        "Price": 26.61,
        "Price Chng % (Price Change %)": 0.0023,
        "Price Chng $ (Price Change $)": 0.06,
        "Mkt Val (Market Value)": 15610.16,
        "Day Chng % (Day Change %)": 0.0023,
        "Day Chng $ (Day Change $)": 35.2,
        "Cost Basis": 15473.75,
        "Gain % (Gain/Loss %)": 0.0088,
        "Gain $ (Gain/Loss $)": 136.41,
        "Ratings": null,
        "Reinvest?": "Yes",
        "Reinvest Capital Gains?": null,
        "% of Acct (% of Account)": 0.043,
        "Security Type": "ETFs & Closed End Funds"
      },
      "VNQ": {
        "Description": "VANGUARD REAL ESTATE ETF",
        "Qty (Quantity)": 197.0399,
        "Price": 98.6,
        "Price Chng % (Price Change %)": 0.0064,
        "Price Chng $ (Price Change $)": 0.63,
        "Mkt Val (Market Value)": 19428.13,
        "Day Chng % (Day Change %)": 0.0064,
        "Day Chng $ (Day Change $)": 124.14,
        "Cost Basis": 16395.49,
        "Gain % (Gain/Loss %)": 0.185,
        "Gain $ (Gain/Loss $)": 3032.64,
        "Ratings": null,
        "Reinvest?": "Yes",
        "Reinvest Capital Gains?": null,
        "% of Acct (% of Account)": 0.0535,
        "Security Type": "ETFs & Closed End Funds"
      },
      "VNQI": {
        "Description": "VANGUARD GLBAL EX US REAL ESTATE ETF",
        "Qty (Quantity)": 244.482,
        "Price": 43.2,
        "Price Chng % (Price Change %)": 0.0131,
        "Price Chng $ (Price Change $)": 0.56,
        "Mkt Val (Market Value)": 10561.62,
        "Day Chng % (Day Change %)": 0.0131,
        "Day Chng $ (Day Change $)": 136.91,
        "Cost Basis": 10136.71,
        "Gain % (Gain/Loss %)": 0.04190000000000001,
        "Gain $ (Gain/Loss $)": 424.91,
        "Ratings": null,
        "Reinvest?": "Yes",
        "Reinvest Capital Gains?": null,
        "% of Acct (% of Account)": 0.0291,
        "Security Type": "ETFs & Closed End Funds"
      },
      "DFVEX": {
        "Description": "DFA US VECTOR EQUITY I",
        "Qty (Quantity)": 8,
        "Price": 28.95,
        "Price Chng % (Price Change %)": -0.0024,
        "Price Chng $ (Price Change $)": -0.07,
        "Mkt Val (Market Value)": 232360.72,
        "Day Chng % (Day Change %)": -0.0024,
        "Day Chng $ (Day Change $)": -561.84,
        "Cost Basis": 165715.92,
        "Gain % (Gain/Loss %)": 0.4022,
        "Gain $ (Gain/Loss $)": 66644.8,
        "Ratings": 4,
        "Reinvest?": "No",
        "Reinvest Capital Gains?": "Yes",
        "% of Acct (% of Account)": 0.6394,
        "Security Type": "Mutual Fund"
      },
      "DFVQX": {
        "Description": "DFA INTERNATIONAL VECTOR EQUITY I",
        "Qty (Quantity)": 4,
        "Price": 13.86,
        "Price Chng % (Price Change %)": 0.0051,
        "Price Chng $ (Price Change $)": 0.07,
        "Mkt Val (Market Value)": 64752.34,
        "Day Chng % (Day Change %)": 0.0051,
        "Day Chng $ (Day Change $)": 327.03,
        "Cost Basis": 60714.12,
        "Gain % (Gain/Loss %)": 0.0665,
        "Gain $ (Gain/Loss $)": 4038.22,
        "Ratings": 3,
        "Reinvest?": "No",
        "Reinvest Capital Gains?": "Yes",
        "% of Acct (% of Account)": 0.1782,
        "Security Type": "Mutual Fund"
      },
      "Cash & Cash Investments": {
        "Description": null,
        "Qty (Quantity)": null,
        "Price": null,
        "Price Chng % (Price Change %)": null,
        "Price Chng $ (Price Change $)": null,
        "Mkt Val (Market Value)": 1499.62,
        "Day Chng % (Day Change %)": 0,
        "Day Chng $ (Day Change $)": 0,
        "Cost Basis": null,
        "Gain % (Gain/Loss %)": null,
        "Gain $ (Gain/Loss $)": null,
        "Ratings": null,
        "Reinvest?": null,
        "Reinvest Capital Gains?": null,
        "% of Acct (% of Account)": 0.0040999999999999995,
        "Security Type": "Cash and Money Market"
      },
      "Account Total": {
        "Description": null,
        "Qty (Quantity)": null,
        "Price": null,
        "Price Chng % (Price Change %)": null,
        "Price Chng $ (Price Change $)": null,
        "Mkt Val (Market Value)": 363420.47,
        "Day Chng % (Day Change %)": 0.0003,
        "Day Chng $ (Day Change $)": 113.83,
        "Cost Basis": 287215.89,
        "Gain % (Gain/Loss %)": 0.2601,
        "Gain $ (Gain/Loss $)": 74704.96,
        "Ratings": null,
        "Reinvest?": null,
        "Reinvest Capital Gains?": null,
        "% of Acct (% of Account)": null,
        "Security Type": null
      }
    },
    "Roth": {
      "VNQ": {
        "Description": "VANGUARD REAL ESTATE ETF",
        "Qty (Quantity)": 237.4242,
        "Price": 98.6,
        "Price Chng % (Price Change %)": 0.0064,
        "Price Chng $ (Price Change $)": 0.63,
        "Mkt Val (Market Value)": 23410.03,
        "Day Chng % (Day Change %)": 0.0064,
        "Day Chng $ (Day Change $)": 149.58,
        "Cost Basis": 20942.18,
        "Gain % (Gain/Loss %)": 0.11779999999999999,
        "Gain $ (Gain/Loss $)": 2467.85,
        "Ratings": null,
        "Reinvest?": "Yes",
        "Reinvest Capital Gains?": null,
        "% of Acct (% of Account)": 0.9201999999999999,
        "Security Type": "ETFs & Closed End Funds"
      },
      "VNQI": {
        "Description": "VANGUARD GLBAL EX US REAL ESTATE ETF",
        "Qty (Quantity)": 47,
        "Price": 43.2,
        "Price Chng % (Price Change %)": 0.0131,
        "Price Chng $ (Price Change $)": 0.56,
        "Mkt Val (Market Value)": 2030.4,
        "Day Chng % (Day Change %)": 0.0131,
        "Day Chng $ (Day Change $)": 26.32,
        "Cost Basis": 2221.48,
        "Gain % (Gain/Loss %)": -0.086,
        "Gain $ (Gain/Loss $)": -191.08,
        "Ratings": null,
        "Reinvest?": "No",
        "Reinvest Capital Gains?": null,
        "% of Acct (% of Account)": 0.07980000000000001,
        "Security Type": "ETFs & Closed End Funds"
      },
      "Cash & Cash Investments": {
        "Description": null,
        "Qty (Quantity)": null,
        "Price": null,
        "Price Chng % (Price Change %)": null,
        "Price Chng $ (Price Change $)": null,
        "Mkt Val (Market Value)": 0.7,
        "Day Chng % (Day Change %)": 0,
        "Day Chng $ (Day Change $)": 0,
        "Cost Basis": null,
        "Gain % (Gain/Loss %)": null,
        "Gain $ (Gain/Loss $)": null,
        "Ratings": null,
        "Reinvest?": null,
        "Reinvest Capital Gains?": null,
        "% of Acct (% of Account)": 0,
        "Security Type": "Cash and Money Market"
      },
      "Account Total": {
        "Description": null,
        "Qty (Quantity)": null,
        "Price": null,
        "Price Chng % (Price Change %)": null,
        "Price Chng $ (Price Change $)": null,
        "Mkt Val (Market Value)": 25441.13,
        "Day Chng % (Day Change %)": 0.006999999999999999,
        "Day Chng $ (Day Change $)": 175.9,
        "Cost Basis": 23163.66,
        "Gain % (Gain/Loss %)": 0.0983,
        "Gain $ (Gain/Loss $)": 2276.77,
        "Ratings": null,
        "Reinvest?": null,
        "Reinvest Capital Gains?": null,
        "% of Acct (% of Account)": null,
        "Security Type": null
      }
    },
    "TRS": {
      "DFAE": {
        "Description": "DIMENSIONAL EMERG CORE EQY MRKT ETF",
        "Qty (Quantity)": 489,
        "Price": 25.81,
        "Price Chng % (Price Change %)": 0.0016,
        "Price Chng $ (Price Change $)": 0.04,
        "Mkt Val (Market Value)": 12621.09,
        "Day Chng % (Day Change %)": 0.0016,
        "Day Chng $ (Day Change $)": 19.56,
        "Cost Basis": 12272.86,
        "Gain % (Gain/Loss %)": 0.028399999999999998,
        "Gain $ (Gain/Loss $)": 348.23,
        "Ratings": null,
        "Reinvest?": "No",
        "Reinvest Capital Gains?": null,
        "% of Acct (% of Account)": 0.0323,
        "Security Type": "ETFs & Closed End Funds"
      },
      "DFAX": {
        "Description": "DIMENSIONAL WLD EX US CREQ 2 ETF",
        "Qty (Quantity)": 561,
        "Price": 25.52,
        "Price Chng % (Price Change %)": 0.004699999999999999,
        "Price Chng $ (Price Change $)": 0.12,
        "Mkt Val (Market Value)": 14316.72,
        "Day Chng % (Day Change %)": 0.004699999999999999,
        "Day Chng $ (Day Change $)": 67.32,
        "Cost Basis": 13794.57,
        "Gain % (Gain/Loss %)": 0.0379,
        "Gain $ (Gain/Loss $)": 522.15,
        "Ratings": null,
        "Reinvest?": "No",
        "Reinvest Capital Gains?": null,
        "% of Acct (% of Account)": 0.036699999999999997,
        "Security Type": "ETFs & Closed End Funds"
      },
      "VNQI": {
        "Description": "VANGUARD GLBAL EX US REAL ESTATE ETF",
        "Qty (Quantity)": 8,
        "Price": 43.2,
        "Price Chng % (Price Change %)": 0.0131,
        "Price Chng $ (Price Change $)": 0.56,
        "Mkt Val (Market Value)": 345.6,
        "Day Chng % (Day Change %)": 0.0131,
        "Day Chng $ (Day Change $)": 4.48,
        "Cost Basis": 470.43,
        "Gain % (Gain/Loss %)": -0.26539999999999997,
        "Gain $ (Gain/Loss $)": -124.83,
        "Ratings": null,
        "Reinvest?": "No",
        "Reinvest Capital Gains?": null,
        "% of Acct (% of Account)": 0.0009,
        "Security Type": "ETFs & Closed End Funds"
      },
      "VTEB": {
        "Description": "VANGUARD MUNI BND TAX EXEMPT ETF",
        "Qty (Quantity)": 153,
        "Price": 50.94,
        "Price Chng % (Price Change %)": 0.0016,
        "Price Chng $ (Price Change $)": 0.08,
        "Mkt Val (Market Value)": 7793.82,
        "Day Chng % (Day Change %)": 0.0016,
        "Day Chng $ (Day Change $)": 12.24,
        "Cost Basis": 7759.03,
        "Gain % (Gain/Loss %)": 0.0045000000000000005,
        "Gain $ (Gain/Loss $)": 34.79,
        "Ratings": null,
        "Reinvest?": "No",
        "Reinvest Capital Gains?": null,
        "% of Acct (% of Account)": 0.02,
        "Security Type": "ETFs & Closed End Funds"
      },
      "DFCEX": {
        "Description": "DFA EMERGING MARKETS CORE EQUITY I",
        "Qty (Quantity)": 747,
        "Price": 23.84,
        "Price Chng % (Price Change %)": -0.0008,
        "Price Chng $ (Price Change $)": -0.02,
        "Mkt Val (Market Value)": 17808.48,
        "Day Chng % (Day Change %)": -0.0008,
        "Day Chng $ (Day Change $)": -14.94,
        "Cost Basis": 14647.25,
        "Gain % (Gain/Loss %)": 0.2158,
        "Gain $ (Gain/Loss $)": 3161.23,
        "Ratings": 4,
        "Reinvest?": "No",
        "Reinvest Capital Gains?": "No",
        "% of Acct (% of Account)": 0.045599999999999995,
        "Security Type": "Mutual Fund"
      },
      "DFVEX": {
        "Description": "DFA US VECTOR EQUITY I",
        "Qty (Quantity)": 1,
        "Price": 28.95,
        "Price Chng % (Price Change %)": -0.0024,
        "Price Chng $ (Price Change $)": -0.07,
        "Mkt Val (Market Value)": 50286.15,
        "Day Chng % (Day Change %)": -0.0024,
        "Day Chng $ (Day Change $)": -121.59,
        "Cost Basis": 40255.84,
        "Gain % (Gain/Loss %)": 0.2492,
        "Gain $ (Gain/Loss $)": 10030.31,
        "Ratings": 4,
        "Reinvest?": "No",
        "Reinvest Capital Gains?": "No",
        "% of Acct (% of Account)": 0.12869999999999998,
        "Security Type": "Mutual Fund"
      },
      "DFVQX": {
        "Description": "DFA INTERNATIONAL VECTOR EQUITY I",
        "Qty (Quantity)": 4,
        "Price": 13.86,
        "Price Chng % (Price Change %)": 0.0051,
        "Price Chng $ (Price Change $)": 0.07,
        "Mkt Val (Market Value)": 60914.7,
        "Day Chng % (Day Change %)": 0.0051,
        "Day Chng $ (Day Change $)": 307.65,
        "Cost Basis": 53288.14,
        "Gain % (Gain/Loss %)": 0.1431,
        "Gain $ (Gain/Loss $)": 7626.56,
        "Ratings": 3,
        "Reinvest?": "No",
        "Reinvest Capital Gains?": "No",
        "% of Acct (% of Account)": 0.1559,
        "Security Type": "Mutual Fund"
      },
      "ORTYX": {
        "Description": "NYLI MACKAY OREGON MUNI CLASS I",
        "Qty (Quantity)": 836,
        "Price": 10.32,
        "Price Chng % (Price Change %)": 0.0019,
        "Price Chng $ (Price Change $)": 0.02,
        "Mkt Val (Market Value)": 8627.52,
        "Day Chng % (Day Change %)": 0.0019,
        "Day Chng $ (Day Change $)": 16.72,
        "Cost Basis": 9068.04,
        "Gain % (Gain/Loss %)": -0.048600000000000004,
        "Gain $ (Gain/Loss $)": -440.52,
        "Ratings": 3,
        "Reinvest?": "No",
        "Reinvest Capital Gains?": "No",
        "% of Acct (% of Account)": 0.022099999999999998,
        "Security Type": "Mutual Fund"
      },
      "VWITX": {
        "Description": "VANGUARD INTERM-TERM TX-EX INV",
        "Qty (Quantity)": 433,
        "Price": 13.71,
        "Price Chng % (Price Change %)": 0.0015,
        "Price Chng $ (Price Change $)": 0.02,
        "Mkt Val (Market Value)": 5936.43,
        "Day Chng % (Day Change %)": 0.0015,
        "Day Chng $ (Day Change $)": 8.66,
        "Cost Basis": 6398.65,
        "Gain % (Gain/Loss %)": -0.0722,
        "Gain $ (Gain/Loss $)": -462.22,
        "Ratings": 4,
        "Reinvest?": "No",
        "Reinvest Capital Gains?": "No",
        "% of Acct (% of Account)": 0.0152,
        "Security Type": "Mutual Fund"
      },
      "VWIUX": {
        "Description": "VANGUARD INTERM-TERM TX-EX ADM",
        "Qty (Quantity)": 224,
        "Price": 13.71,
        "Price Chng % (Price Change %)": 0.0015,
        "Price Chng $ (Price Change $)": 0.02,
        "Mkt Val (Market Value)": 3071.04,
        "Day Chng % (Day Change %)": 0.0015,
        "Day Chng $ (Day Change $)": 4.48,
        "Cost Basis": 3225.6,
        "Gain % (Gain/Loss %)": -0.0479,
        "Gain $ (Gain/Loss $)": -154.56,
        "Ratings": 4,
        "Reinvest?": "No",
        "Reinvest Capital Gains?": "No",
        "% of Acct (% of Account)": 0.0079,
        "Security Type": "Mutual Fund"
      },
      "VTWAX": {
        "Description": "VANGUARD INTERM-TERM TX-EX ADM",
        "Qty (Quantity)": 224,
        "Price": 13.71,
        "Price Chng % (Price Change %)": 0.0015,
        "Price Chng $ (Price Change $)": 0.02,
        "Mkt Val (Market Value)": 0,
        "Day Chng % (Day Change %)": 0.0015,
        "Day Chng $ (Day Change $)": 4.48,
        "Cost Basis": 3225.6,
        "Gain % (Gain/Loss %)": -0.0479,
        "Gain $ (Gain/Loss $)": -154.56,
        "Ratings": 4,
        "Reinvest?": "No",
        "Reinvest Capital Gains?": "No",
        "% of Acct (% of Account)": 0.0079,
        "Security Type": "Mutual Fund"
      },
      "VGSLX": {
        "Description": "VANGUARD INTERM-TERM TX-EX ADM",
        "Qty (Quantity)": 224,
        "Price": 13.71,
        "Price Chng % (Price Change %)": 0.0015,
        "Price Chng $ (Price Change $)": 0.02,
        "Mkt Val (Market Value)": 0,
        "Day Chng % (Day Change %)": 0.0015,
        "Day Chng $ (Day Change $)": 4.48,
        "Cost Basis": 3225.6,
        "Gain % (Gain/Loss %)": -0.0479,
        "Gain $ (Gain/Loss $)": -154.56,
        "Ratings": 4,
        "Reinvest?": "No",
        "Reinvest Capital Gains?": "No",
        "% of Acct (% of Account)": 0.0079,
        "Security Type": "Mutual Fund"
      },
      "VEMAX": {
        "Description": "VANGUARD INTERM-TERM TX-EX ADM",
        "Qty (Quantity)": 224,
        "Price": 13.71,
        "Price Chng % (Price Change %)": 0.0015,
        "Price Chng $ (Price Change $)": 0.02,
        "Mkt Val (Market Value)": 0,
        "Day Chng % (Day Change %)": 0.0015,
        "Day Chng $ (Day Change $)": 4.48,
        "Cost Basis": 3225.6,
        "Gain % (Gain/Loss %)": -0.0479,
        "Gain $ (Gain/Loss $)": -154.56,
        "Ratings": 4,
        "Reinvest?": "No",
        "Reinvest Capital Gains?": "No",
        "% of Acct (% of Account)": 0.0079,
        "Security Type": "Mutual Fund"
      },
      "VSIAX": {
        "Description": "VANGUARD INTERM-TERM TX-EX ADM",
        "Qty (Quantity)": 224,
        "Price": 13.71,
        "Price Chng % (Price Change %)": 0.0015,
        "Price Chng $ (Price Change $)": 0.02,
        "Mkt Val (Market Value)": 0,
        "Day Chng % (Day Change %)": 0.0015,
        "Day Chng $ (Day Change $)": 4.48,
        "Cost Basis": 3225.6,
        "Gain % (Gain/Loss %)": -0.0479,
        "Gain $ (Gain/Loss $)": -154.56,
        "Ratings": 4,
        "Reinvest?": "No",
        "Reinvest Capital Gains?": "No",
        "% of Acct (% of Account)": 0.0079,
        "Security Type": "Mutual Fund"
      },
      "VBTLX": {
        "Description": "VANGUARD INTERM-TERM TX-EX ADM",
        "Qty (Quantity)": 224,
        "Price": 13.71,
        "Price Chng % (Price Change %)": 0.0015,
        "Price Chng $ (Price Change $)": 0.02,
        "Mkt Val (Market Value)": 0,
        "Day Chng % (Day Change %)": 0.0015,
        "Day Chng $ (Day Change $)": 4.48,
        "Cost Basis": 3225.6,
        "Gain % (Gain/Loss %)": -0.0479,
        "Gain $ (Gain/Loss $)": -154.56,
        "Ratings": 4,
        "Reinvest?": "No",
        "Reinvest Capital Gains?": "No",
        "% of Acct (% of Account)": 0.0079,
        "Security Type": "Mutual Fund"
      },
      "Cash & Cash Investments": {
        "Description": null,
        "Qty (Quantity)": null,
        "Price": null,
        "Price Chng % (Price Change %)": null,
        "Price Chng $ (Price Change $)": null,
        "Mkt Val (Market Value)": 208906.44,
        "Day Chng % (Day Change %)": 0,
        "Day Chng $ (Day Change $)": 0,
        "Cost Basis": null,
        "Gain % (Gain/Loss %)": null,
        "Gain $ (Gain/Loss $)": null,
        "Ratings": null,
        "Reinvest?": null,
        "Reinvest Capital Gains?": null,
        "% of Acct (% of Account)": 0.5347999999999999,
        "Security Type": "Cash and Money Market"
      },
      "Account Total": {
        "Description": null,
        "Qty (Quantity)": null,
        "Price": null,
        "Price Chng % (Price Change %)": null,
        "Price Chng $ (Price Change $)": null,
        "Mkt Val (Market Value)": 390627.99,
        "Day Chng % (Day Change %)": 0.0008,
        "Day Chng $ (Day Change $)": 304.58,
        "Cost Basis": 161180.41,
        "Gain % (Gain/Loss %)": 0.1274,
        "Gain $ (Gain/Loss $)": 20541.14,
        "Ratings": null,
        "Reinvest?": null,
        "Reinvest Capital Gains?": null,
        "% of Acct (% of Account)": null,
        "Security Type": null
      }
    }
  });
});
